export enum Screens {
    REGISTER = "REGISTER",
    LOGIN = "LOGIN",
    DASHBOARD = "DASHBOARD",
    FINDPLAYER = "FINDPLAYER",
    PROFILESCREEN = "PROFILESCREEN",
    SEARCHBAR = "SEARCHBAR",
    LANDING = "LANDING"

  }